default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: dmitro24

development:
  <<: *default
  database: work

test:
  <<: *default
  database: work_test

production:
  <<: *default
  database: work_production
  username: postgres
  password: <%= ENV['APP_DATABASE_PASSWORD'] %>